name: metrics

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"
  push:
    branches:
      - master

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: d12frosted/github-profile-summary-cards@1cf2e151a9b9d88d9105ce8927c4d3c1b7ee1a3d
        env:
          GITHUB_TOKEN: ${{ secrets.METRICS_TOKEN }}
        with:
          USERNAME: ${{ github.repository_owner }}    
