name: metrics

on:
  workflow_dispatch:
  # schedule:
  #  - cron: "0 * * * *"
  push:
    branches:
      - master

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # - uses: vn7n24fzkq/github-profile-summary-cards@release
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.METRICS_TOKEN }}
      #   with:
      #     USERNAME: ${{ github.repository_owner }}    
